version: '3'
services:
  connector-crowdsec:
    image: opencti/connector-crowdsec:6.0.10
    environment:
      - OPENCTI_URL=http://opencti:8080 # default OpenCTI API URL
      - OPENCTI_TOKEN=ChangeMe # Add OpenCTI API token here
      - CONNECTOR_ID=ChangeMe # Add connector ID (any valid UUID v4)
      - CROWDSEC_MAX_TLP=TLP:AMBER
      - CONNECTOR_TYPE=INTERNAL_ENRICHMENT
      - CONNECTOR_NAME=CrowdSec
      - CROWDSEC_NAME=CrowdSec
      - CROWDSEC_DESCRIPTION=crowdsec_cti_enrichment
      - CONNECTOR_SCOPE=IPv4-Addr # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
      - CONNECTOR_AUTO=true
      - CROWDSEC_KEY=ChangeMe #Add API Key
      - CROWDSEC_VERSION=v2 #v2 is the only supported version for now
      - CROWDSEC_LABELS_SCENARIO_USE=true # Enable or disable scenario labels
      - CROWDSEC_LABELS_SCENARIO_ONLY_NAME=false # Create only labels for scenario names (and not scenario label)
      - CROWDSEC_LABELS_SCENARIO_COLOR='#2E2A14' # Color code for scenario labels (Dark Olive Green)
      - CROWDSEC_LABELS_CVE_USE=true # Enable or disable CVE labels
      - CROWDSEC_LABELS_CVE_COLOR='#800080' # Color code for CVE labels (Purple)
      - CROWDSEC_LABELS_MITRE_USE=false # Enable or disable mitre techniques labels
      - CROWDSEC_LABELS_MITRE_COLOR='#000080' # Color code for mitre techniques labels (Navy Blue)
      - CROWDSEC_LABELS_BEHAVIOR_USE=false # Enable or disable behavior labels
      - CROWDSEC_LABELS_BEHAVIOR_COLOR='#808000' # Color code for behavior labels (Olive)
      - CROWDSEC_LABELS_REPUTATION_USE=false # Enable or disable reputation labels
      - CROWDSEC_LABELS_REPUTATION_MALICIOUS_COLOR='#FF0000' # Color code for malicious reputation label (Red)
      - CROWDSEC_LABELS_REPUTATION_SUSPICIOUS_COLOR='#FFA500' # Color code for suspicious reputation label (Orange)
      - CROWDSEC_LABELS_REPUTATION_SAFE_COLOR='#00BFFF' # Color code for safe reputation label (Deep Sky Blue)
      - CROWDSEC_LABELS_REPUTATION_KNOWN_COLOR='#808080' # Color code for known reputation label (Gray)
      - CROWDSEC_INDICATOR_CREATE_FROM='' # List of reputations to create indicators from (malicious, suspicious, known, safe) separated by comma
      - CROWDSEC_ATTACK_PATTERN_CREATE_FROM_MITRE=true # Create attack patterns from MITRE techniques (available only if indicator is created)
    restart: always
  # If you add it to your OpenCTI docker-compose, add depends_on: - opencti
